import type { IFishObject } from '@/interfaces/IFishObject'

export const fishDictionary: IFishObject[] = [
  //------------------------------------------| XS Rainbow
  {
    name: 'xs-rainbow',
    height: 20,
    width: 40,
    imagePath: 'images/xs-rainbow-right.svg',
    goesRight: true,
    speed: 5,
    top: 0,
    left: 0,
    headX: 30,
    headY: 10,
    headR: 10,
    bodyX: 20,
    bodyY: 10,
    bodyR: 10
  },
  {
    name: 'xs-rainbow',
    height: 20,
    width: 40,
    imagePath: 'images/xs-rainbow-left.svg',
    goesRight: false,
    speed: 5,
    top: 0,
    left: 0,
    headX: 10,
    headY: 10,
    headR: 10,
    bodyX: 20,
    bodyY: 10,
    bodyR: 10
  },
  //------------------------------------------| XS Clown
  {
    name: 'xs-clown',
    height: 30,
    width: 59,
    imagePath: 'images/xs-clown-right.svg',
    goesRight: true,
    speed: 3,
    top: 0,
    left: 0,
    headX: 44,
    headY: 15,
    headR: 15,
    bodyX: 30,
    bodyY: 15,
    bodyR: 15
  },
  {
    name: 'xs-clown',
    height: 30,
    width: 59,
    imagePath: 'images/xs-clown-left.svg',
    goesRight: false,
    speed: 3,
    top: 0,
    left: 0,
    headX: 15,
    headY: 15,
    headR: 15,
    bodyX: 30,
    bodyY: 15,
    bodyR: 15
  },
  //------------------------------------------| XS Fire
  {
    name: 'xs-fire',
    height: 40,
    width: 71,
    imagePath: 'images/xs-fire-right.svg',
    goesRight: true,
    speed: 4,
    top: 0,
    left: 0,
    headX: 56,
    headY: 25,
    headR: 15,
    bodyX: 35,
    bodyY: 20,
    bodyR: 20
  },
  {
    name: 'xs-fire',
    height: 40,
    width: 71,
    imagePath: 'images/xs-fire-left.svg',
    goesRight: false,
    speed: 2,
    top: 0,
    left: 0,
    headX: 15,
    headY: 25,
    headR: 15,
    bodyX: 35,
    bodyY: 20,
    bodyR: 20
  },
  //------------------------------------------| XS Blue
  {
    name: 'xs-blue',
    height: 60,
    width: 129,
    imagePath: 'images/xs-blue-right.svg',
    goesRight: true,
    speed: 2,
    top: 0,
    left: 0,
    headX: 99,
    headY: 30,
    headR: 30,
    bodyX: 65,
    bodyY: 30,
    bodyR: 30
  },
  {
    name: 'xs-blue',
    height: 60,
    width: 129,
    imagePath: 'images/xs-blue-left.svg',
    goesRight: false,
    speed: 4,
    top: 0,
    left: 0,
    headX: 30,
    headY: 30,
    headR: 30,
    bodyX: 65,
    bodyY: 30,
    bodyR: 30
  },
  //------------------------------------------| XS Spinosaurus
  {
    name: 'xs-spino',
    height: 70,
    width: 111,
    imagePath: 'images/xs-spinosaurus-right.svg',
    goesRight: true,
    speed: 3,
    top: 0,
    left: 0,
    headX: 76,
    headY: 35,
    headR: 35,
    bodyX: 65,
    bodyY: 35,
    bodyR: 35
  },
  {
    name: 'xs-spino',
    height: 70,
    width: 111,
    imagePath: 'images/xs-spinosaurus-left.svg',
    goesRight: false,
    speed: 3,
    top: 0,
    left: 0,
    headX: 35,
    headY: 35,
    headR: 35,
    bodyX: 65,
    bodyY: 35,
    bodyR: 35
  },
  //------------------------------------------| XS Bossy
  {
    name: 'xs-bossy',
    height: 80,
    width: 156,
    imagePath: 'images/xs-bossy-right.svg',
    goesRight: true,
    speed: 4,
    top: 0,
    left: 0,
    headX: 116,
    headY: 40,
    headR: 40,
    bodyX: 78,
    bodyY: 40,
    bodyR: 40
  },
  {
    name: 'xs-bossy',
    height: 80,
    width: 156,
    imagePath: 'images/xs-bossy-left.svg',
    goesRight: false,
    speed: 4,
    top: 0,
    left: 0,
    headX: 40,
    headY: 40,
    headR: 40,
    bodyX: 78,
    bodyY: 40,
    bodyR: 40
  },
  //------------------------------------------| XS Nosy
  {
    name: 'xs-nosy',
    height: 100,
    width: 126,
    imagePath: 'images/s-nosy-right.svg',
    goesRight: true,
    speed: 5,
    top: 0,
    left: 0,
    headX: 86,
    headY: 60,
    headR: 40,
    bodyX: 63,
    bodyY: 50,
    bodyR: 50
  },
  {
    name: 'xs-nosy',
    height: 100,
    width: 126,
    imagePath: 'images/s-nosy-left.svg',
    goesRight: false,
    speed: 5,
    top: 0,
    left: 0,
    headX: 40,
    headY: 60,
    headR: 40,
    bodyX: 63,
    bodyY: 50,
    bodyR: 50
  },
  //------------------------------------------| S Sailfish
  {
    name: 's-sailfish',
    height: 120,
    width: 105,
    imagePath: 'images/s-sailfish-right.svg',
    goesRight: true,
    speed: 4,
    top: 0,
    left: 0,
    headX: 65,
    headY: 60,
    headR: 40,
    bodyX: 52,
    bodyY: 60,
    bodyR: 53
  },
  {
    name: 's-sailfish',
    height: 120,
    width: 105,
    imagePath: 'images/s-sailfish-left.svg',
    goesRight: false,
    speed: 4,
    top: 0,
    left: 0,
    headX: 40,
    headY: 60,
    headR: 40,
    bodyX: 52,
    bodyY: 60,
    bodyR: 53
  },
  //------------------------------------------| S Barrel
  {
    name: 's-barrel',
    height: 110,
    width: 157,
    imagePath: 'images/s-barrel-right.svg',
    goesRight: true,
    speed: 7,
    top: 0,
    left: 0,
    headX: 102,
    headY: 55,
    headR: 55,
    bodyX: 79,
    bodyY: 60,
    bodyR: 53
  },
  {
    name: 's-barrel',
    height: 110,
    width: 157,
    imagePath: 'images/s-barrel-left.svg',
    goesRight: false,
    speed: 7,
    top: 0,
    left: 0,
    headX: 55,
    headY: 55,
    headR: 55,
    bodyX: 79,
    bodyY: 60,
    bodyR: 53
  },
  //------------------------------------------| L Hammer
  {
    name: 'l-hammer',
    height: 300,
    width: 527,
    imagePath: 'images/l-hammer-right.svg',
    goesRight: true,
    speed: 8,
    top: 0,
    left: 0,
    headX: 407,
    headY: 200,
    headR: 75,
    bodyX: 213,
    bodyY: 150,
    bodyR: 150
  },
  {
    name: 'l-hammer',
    height: 300,
    width: 527,
    imagePath: 'images/l-hammer-left.svg',
    goesRight: false,
    speed: 8,
    top: 0,
    left: 0,
    headX: 120,
    headY: 200,
    headR: 75,
    bodyX: 213,
    bodyY: 150,
    bodyR: 150
  }
]
